#!/bin/bash

if [ -z "$1" ]; then
  echo "add_to_bashrc: Usage: $0 'line_to_add'"
  exit 1
fi

[ -f ~/.bashrc ] || : > ~/.bashrc

line="$1"
if ! grep -Fxq "$line" ~/.bashrc; then
  echo "$line" >> ~/.bashrc
fi