#!/bin/bash

config="config/database.yml"
if [ ! -f "$config" ]; then
  echo "No $config file present"
  exit 1
fi

read -p "Are you sure you want to overwrite heroku remote database? (y/n): " CONFIRMATION
if [[ ! "$CONFIRMATION" =~ ^[Yy]$ ]]; then
  exit 1
fi

user=$(grep -E "^\s*user:" $config | awk '{print $2}' | head -n 1) # use head incase there are multiple users
db=$(grep -E "^\s*database:" $config | awk '{print $2}' | head -n 1)

echo "Capturing backup"
heroku pg:backups:capture

echo "Creating local dump"
rm -rf local.dump
pg_dump --verbose --clean --no-acl --no-owner -b -F c -h localhost -U "$user" -d "$db" -f local.dump
# -F c = format=pg_restore

echo "Uploading to heroku"
DB_URL=$(heroku config:get DATABASE_URL)
DB_QUERY='postgres://([^:]+):([^@]+)@([^:]+):([0-9]+)/([^?]+)'
DB_USER=$(echo $DB_URL | sed -E "s|$DB_QUERY|\1|")
DB_PASS=$(echo $DB_URL | sed -E "s|$DB_QUERY|\2|")
DB_HOST=$(echo $DB_URL | sed -E "s|$DB_QUERY|\3|")
DB_PORT=$(echo $DB_URL | sed -E "s|$DB_QUERY|\4|")
DB_NAME=$(echo $DB_URL | sed -E "s|$DB_QUERY|\5|")

PGPASSWORD="$DB_PASS" pg_restore --verbose --clean --no-acl --no-owner -h "$DB_HOST" -U "$DB_USER" -d "$DB_NAME" local.dump
