# Set programs that you use
$terminal = kitty
$fileManager = dolphin
$menu = wofi --show drun

# Some default env vars.
env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24
env = bitdepth,10

source = $HOME/.config/hypr/binds.conf




# See https://wiki.hyprland.org/Configuring/Monitors/
monitor = DP-1,     1920x1080@60,  0x0,    1 # Acer
monitor = DP-2,     2560x1440@144, 1920x0, 1 # LG
monitor = HDMI-A-1, 1920x1080@60,  4480x0, 1 # Asus
monitor=,preferred,auto,auto
workspace = 1, monitor:DP-1
workspace = 2, monitor:DP-2
workspace = 3, monitor:HDMI-A-1


# See https://wiki.hyprland.org/Configuring/Keywords/ for more

# Execute your favorite apps at launch
# exec-once = . ~/.pyenv/versions/waybar/bin/activate; waybar
exec-once = /usr/bin/gjs -m /usr/bin/ags --config $HOME/.dotfiles/ags/statusbar.js
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = dunst
exec-once = hyprpaper


# https://wiki.hyprland.org/Configuring/Variables/#input
input {
    kb_layout = us
    follow_mouse = 1

    touchpad {
        natural_scroll = no
        tap-to-click = true
    }

    sensitivity = -0.5 # -1.0 to 1.0, 0 means no modification.
}

cursor {
  no_hardware_cursors = true
}

# https://wiki.hyprland.org/Configuring/Variables/#general
general {
    gaps_out = 10
    border_size = 2
    no_focus_fallback = true
    resize_on_border = true

    layout = dwindle
    allow_tearing = true
}

# https://wiki.hyprland.org/Configuring/Variables/#decoration
decoration {

    rounding = 10
    
    blur {
        enabled = false
        size = 10
        passes = 1
    }
}

# https://wiki.hyprland.org/Configuring/Animations/
animations {
    enabled = yes
    bezier = myBezier, 0.05, 0.9, 0.1, 1.05

    animation = windows, 1, 7, myBezier
    animation = windowsOut, 1, 7, default, popin 80%
    animation = border, 1, 10, default
    animation = borderangle, 1, 8, default
    animation = fade, 1, 7, default
    animation = workspaces, 1, 6, default
}

dwindle {
    # See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
    # pseudotile = yes # master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = yes # you probably want this
}

gestures {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more
    workspace_swipe = off
}

misc {
  disable_hyprland_logo = true
}

# Example per-device config
# See https://wiki.hyprland.org/Configuring/Keywords/#per-device-input-configs for more
device {
    name = epic-mouse-v1
    sensitivity = -0.5
}

# windowrulev2 = float,class:^(kitty)$,title:^(kitty)$
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
windowrulev2 = suppressevent maximize, class:.* # You'll probably like this.
windowrulev2 = immediate,class:^(cs2)$
